server:
  # Render가 제공하는 PORT 환경 변수를 사용하도록 수정 (매우 중요)
  port: ${PORT:8080}

spring:
  datasource:
    url: ${DATABASE_URL}
    # Render에 설정한 환경 변수 이름과 반드시 일치해야 합니다.
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      # create는 매번 서버 재시작 시 모든 테이블을 삭제하므로, 개발 초기 단계가 아니라면 update 또는 validate를 권장합니다.
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: false

# OpenAI API 키 설정을 여기에 추가합니다.
# 이 설정은 Render에 있는 OPENAI_API_KEY 환경 변수의 값을 읽어옵니다.
openai:
  api:
    key: ${OPENAI_API_KEY}

logging:
  level:
    org:
      hibernate:
        SQL: INFO
    root: INFO

app:
  upload:
    dir: /var/data/uploads