server:
  port: 8080

spring:
  datasource:
    # 2단계에서 Render에 만든 변수 이름과 정확히 일치합니다.
    url: ${DATABASE_URL}
    username: ${MYSQLUSER}
    password: ${MYSQLPASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: false

logging:
  level:
    org.hibernate.SQL: INFO
    root: INFO

app:
  upload:
    dir: /var/data/uploads