server:
  port: ${PORT:8080}

spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${MYSQLUSER}
    password: ${MYSQLPASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: false

openai:
  enabled: ${OPENAI_ENABLED:true}
  model: ${OPENAI_MODEL:gpt-4o-mini}
  api:
    key: ${OPENAI_API_KEY}
    url: ${OPENAI_BASE_URL:https://api.openai.com/v1/chat/completions}
  timeout-seconds: ${OPENAI_TIMEOUT_SECONDS:30}

logging:
  level:
    org.hibernate.SQL: INFO
    root: INFO

app:
  upload:
    dir: /var/data/uploads
